MYSQL_HOST: 192.168.1.226
MYSQL_PORT: 9025
MYSQL_USER_NAME: dev_user
MYSQL_PASS: iui098mm112
REDIS_HOST: 192.168.1.226
REDIS_PORT: 9166
RABBIT_MQ_HOST: 192.168.1.226
RABBIT_MQ_PORT: 5672

server:
  port: 8082

spring:
  application:
    name: scp-workflow
  jpa:
    hibernate:
      ddl-auto: update
    database: MYSQL
  datasource:
    name: test
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/scp_workflow?useUnicode=true&characterEncoding=UTF8
    username: ${MYSQL_USER_NAME:root}
    password: ${MYSQL_PASS:123456}
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
  redis:
    database: 1
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    pool:
        max-active: 20


# 添加下面的代码后，出现了异常
# java.lang.IllegalArgumentException: Mapped Statements collection already contains value for com.bjzhianjia.scp.security.wf.mapper.WfActReModelBeanMapper.selectByPrimaryKey
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.bjzhianjia.scp.security.wf.entity
  

  
# 配置swagger
swagger:
    enabled: true
    base-package: com.bjzhianjia.scp.security.wf
    title: scp-workflow
    version: 1.0.0.SNAPSHOT
    description: 工作流服务
    contact:
        name: workflow


# 配置用户认证和服务认证信息
auth:
  serviceId: scp-auth
  user:
    token-header: Authorization
    limit-expire: 1440 # 一天过去,单位分钟
  client:
    id: scp-workflow
    secret: 123456
    token-header: client-token

logging:
  level:
    com.bjzhianjia.scp.security.wf: DEBUG
    tk.mybatis: DEBUG
    org.activiti: debug
    org.framework: debug

mapper:  
  mappers: com.bjzhianjia.scp.security.common.mapper.CommonMapper
  