server:
    port: 9998

logging:
    level:
        org.springframework.core: INFO

spring:
    application:
        name: scp-data-provider

eureka:
    instance:
        preferIpAddress: true
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
