# 具体看类:CloudStorageConfig
oss:
  type: 8 # 类型 1：七牛  2：阿里云  3：腾讯云   6:本地  8：fastdfs
  qiniuDomain: http://ofsc32t59.bkt.clouddn.com
  qiniuPrefix: oss
  qiniuAccessKey: FAvmtRaY_yUC6Taj0b3sM8k2Wa6BDOUBy3KVBdT_
  qiniuSecretKey: a0P8OtyJv7weu7_z9YtXzplfcIzKtcHR2da_qemk
  qiniuBucketName: image
  fdfsConnectTimeout: 5
  fdfsNetworkTimeout: 30
  fdfsCharset: UTF-8
  fdfsHttpTrackerHttpPort: 8082
  fdfsHttpAntiStealToken: no
  fdfsHttpSecretKey: wbuudsicxhiuaionzihuabnishi
  fdfsTrackerServers: fdfs.lutuo.com:22122
  localStoragePathPrefix: D:/data #  local存储配置
  localIsNameByDate: true

search:
  lucence:
    path: ./lucence/file