logging:
    level:
#        tk.mybatis: DEBUG
        com.bjzhianjia.scp.oss: DEBUG
server:
    port: 9991

spring:
    profiles:
      active: dev
    application:
        name: scp-tool
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: non_null
    redis:
        database: 1
        host: ${REDIS_HOST:localhost}
        port: ${REDIS_PORT:6379}
        pool:
            max-active: 20
    http:
      multipart:
        max-file-size: 10Mb
        max-request-size: 10Mb
# 配置数据库
mybatis:
    mapper-locations: "classpath*:mapper/*.xml"

# 配置swagger
swagger:
    enabled: true
    base-package: com.bjzhianjia.scp.oss
    title: scp-gate
    version: 1.0.0.SNAPSHOT
    description: sssssssssqqqqqq
    contact:
        name: admin

# 配置用户认证和服务认证信息
auth:
  serviceId: scp-auth
  user:
    token-header: Authorization
    limit-expire: 1440 # 一天过去,单位分钟
  client:
    id: scp-tool
    secret: 123456
    token-header: client-token
    
mapper:
  mappers: com.bjzhianjia.scp.security.common.mapper.CommonMapper

# 具体看类:CloudStorageConfig
#oss:
#  type: 8 # 类型 1：七牛  2：阿里云  3：腾讯云
#  qiniuDomain: http://xxxxx
#  qiniuPrefix: xxx
#  qiniuAccessKey: xxxxx
#  qiniuSecretKey: xxxxx
#  qiniuBucketName: xxxx
# (格式：/xxx/xxx)
# localStoragePathPrefix: /xxx/xxx

search:
  lucence:
    path: ./lucence/file